FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD flipkart.jar /opt/flipkart/
EXPOSE 8080
WORKDIR /opt/flipkart/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "flipkart.jar"]
